# coding: utf-8

from __future__ import absolute_import

from swagger_server import util
from swagger_server.models.base_model_ import Model


class Admin(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    
    def __init__(self, data: object = None):  # noqa: E501
        """Admin - a model defined in Swagger

        :param data: The data of this Admin.  # noqa: E501
        :type data: object
        """
        self.swagger_types = {
            'data': object
        }
        
        self.attribute_map = {
            'data': 'data'
        }
        
        self._data = data
    
    @classmethod
    def from_dict(cls, dikt) -> 'Admin':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The admins of this Admin.  # noqa: E501
        :rtype: Admin
        """
        return util.deserialize_model(dikt, cls)
    
    @property
    def data(self) -> object:
        """Gets the data of this Admin.


        :return: The data of this Admin.
        :rtype: object
        """
        return self._data
    
    @data.setter
    def data(self, data: object):
        """Sets the data of this Admin.


        :param data: The data of this Admin.
        :type data: object
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501
        
        self._data = data
